name: test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.0.0
      - uses: erlef/setup-beam@v1
        with:
          otp-version: "24.2"
          elixir-version: "1.13.1"
          gleam-version: "0.19.0-rc3"
      - run: gleam test
      - run: gleam format --check src test
